apiVersion: apps/v1
kind:  ReplicaSet
metadata:
  name:  myweb-rs

spec:
  replicas:  7
  selector:
    matchExpressions: 
      - { key: env,  operator: In, values: [production] }

  template:
    metadata:
      name: myweb-pod
      labels:
        env: production
    spec:           #Specification of the Pod Can contain multiple container or single container pod
      containers:
        - name: myweb-con
          image: ankitjnyadav/apache-webserver-php
